# ${project.name} - ${project.description}
# Project page : https://github.com/XSoussou/ChopChop


# What triggers the tree chopping, different values for this are sneak, unsneak, and any.
# Default: any
activation-mode: any

# Setting this to false will disable the durability calculations and act as if only one block was destroyed.
# Default: true
tools-wear-off: true

# Whether or not the plugin should only work with axes.
# Default: true
only-axes: true

# Set this to false to break an entire tree regardless of what trunk block you destroyed first.
# Default: true
only-break-upwards: true

# Enables the plugin for players in creative mode.
# Default: true
allow-in-creative: true

# Set this to false to not break leaves.
# Default: true
destroy-leaves: true

# Should looted leaves damage tools that have the Silk Touch enchantment.
# Default: true
silk-touch-damage: true

# Enable/disable the plugin for mushrooms.
# Default: true
enable-mushrooms: true

# Allows the plugin to collect anonymous data about the server. Collected data can be found on https://bstats.org/plugin/bukkit/ChopChop/9489
# Default: true
send-metrics: true

# Checks for new updates at server startup and every 6 hours.
# Default: true
enable-updater: true


# Internal use only, do not edit. (Currently not implemented)
config-version: 1
