name: ${project.name}
author: Soussou
description: ${project.description}
version: ${project.version}
api-version: 1.13
main: me.soussou.chopchop.ChopChop
commands:
  chopchop:
    description: Main ${project.name} command
    permission: chopchop.admin
    usage: "§cUsage: /<command> [on | off | reload]"
    aliases: [cc]
permissions:
  chopchop.deny:
    description: Prevents the player from using the plugin
  chopchop.admin:
    description: Allows the use of the /chopchop command